name: synctest

on:
  push: { }
  pull_request: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.event.after }}
  cancel-in-progress: true

jobs:
  test_sync_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4
      - name: Build
        run: make
      - name: Run docker registry
        run: docker run -d -p 5000:5000 --restart=always --name registry registry:2
      - name: Run image-syncer
        run: ./image-syncer --proc=6 --auth=./.github/workflows/config/test-auth.yml --images=./.github/workflows/config/test-images.yml
      - name: Use docker to check result
        run: |
          docker pull localhost:5000/image-syncer-test/alpine:3.18.2 &&
          docker pull localhost:5000/image-syncer-test/olm:v0.18.3 &&
          docker pull localhost:5000/image-syncer-test/hybridnet:v0.8.2 &&
          docker pull localhost:5000/image-syncer-test/hybridnet@sha256:14b267eb38aa85fd12d0e168fffa2d8a6187ac53a14a0212b0d4fce8d729598c &&
          docker pull localhost:5000/image-syncer-test/hybridnet:v0.8.2-test